name: python编译Windows版

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Versatile PyInstaller
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: '3.12'
          spec: 'python.py'
          upload_exe_with_name: 'python'
          options: --onefile, --name "python", --windowed, 
